import random
from locust import HttpUser, task, between

class AgendaUser(HttpUser):
    # Simulate a user waiting 1-5 seconds between actions
    wait_time = between(1, 5)
    
    def on_start(self):
        """Disable SSL verification for the session."""
        self.client.verify = False

    @task(4)
    def list_events(self):
        """Simulate a user viewing their agenda (High frequency)."""
        self.client.get("/api/events")

    @task(1)
    def create_event(self):
        """Simulate a user adding a new task."""
        title = f"Task {random.randint(1000, 9999)}"
        self.client.post("/api/events", json={
            "title": title,
            "description": "Generated by Locust load test"
        })

    @task(1)
    def delete_random_event(self):
        """Simulate a user cleaning up their agenda."""
        # Fetch current events to find an ID to delete
        with self.client.get("/api/events", catch_response=True) as response:
            if response.ok:
                events = response.json()
                if events:
                    event_to_delete = random.choice(events)
                    event_id = event_to_delete['id']
                    self.client.delete(f"/api/events/{event_id}")
            else:
                response.failure("Failed to fetch events for deletion")
